FROM php:7-apache
ADD apache-conf /root/
RUN cat /root/apache-conf | tee -a /etc/apache2/apache2.conf

#ADD init-htaccess.sh /etc/php-init.d/
#ENV keydir /var/keys
#VOLUME "$keydir"

# System Dependencies.
RUN apt-get update && apt-get install -y \
		git \
		imagemagick \
		libicu-dev \
	--no-install-recommends && rm -r /var/lib/apt/lists/*

# Install the PHP extensions we need
RUN docker-php-ext-install mbstring mysqli opcache intl

# Install the default object cache.
RUN pecl install apcu \
    && docker-php-ext-enable apcu
# RUN pecl channel-update pecl.php.net \
# 	&& pecl install apcu-5.1.8 \
# 	&& docker-php-ext-enable apcu

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

# Version
ENV MEDIAWIKI_MAJOR_VERSION 1.33
ENV MEDIAWIKI_BRANCH REL1_33
ENV MEDIAWIKI_VERSION 1.33.0
ENV MEDIAWIKI_SHA512 e31f5d8bd0bef39b9e2db71f129da128d20174f86e6a4799de5e24195bdcbbc06778b978a48073934b6e59d837629d6b83c182c8271b5fb944ef4ce5df856c68

# MediaWiki setup
RUN set -eux; \
  curl -fSL "https://releases.wikimedia.org/mediawiki/${MEDIAWIKI_MAJOR_VERSION}/mediawiki-${MEDIAWIKI_VERSION}.tar.gz" -o mediawiki.tar.gz; \
    echo "${MEDIAWIKI_SHA512} *mediawiki.tar.gz" | sha512sum -c -; \
      tar -x --strip-components=1 -f mediawiki.tar.gz; \
        rm mediawiki.tar.gz; \
          chown -R www-data:www-data extensions skins cache images
